export const MachiningCenters = {
    VerticalMachiningCenters: [
        { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand', pattern: /^[a-zA-Z0-9\s]+$/, maxLength: 50 },
        { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model', pattern: /^[a-zA-Z0-9\s]+$/, maxLength: 50 },
        { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase', pattern: /^[0-9]{4}$/, maxLength: 4 },
        { name: 'duty', label: 'Duty', type: 'select', placeholder: "Please choose type", options: [{ value: 'Manual', label: 'Manual' }, { value: 'Light', label: 'Light' }, { value: 'Medium', label: 'Medium' }, { value: 'Heavy', label: 'Heavy' }] },
        { name: 'no_of_axis', label: 'No. Of Axis', type: 'text', placeholder: "Enter in number", pattern: /^[0-9]{0,4}$/, maxLength: 4 },
        { name: 'table_size', label: 'Table Size', type: 'text', placeholder: "Dimension in mm", pattern: /^(?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 7 },
        { name: 'max_load_on_the_table', label: 'Max Load_on The Table', type: 'text', placeholder: "Enter in kgs", pattern: /^(?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 7 },
        { name: 'x_axis', label: 'X-Axis', type: 'text', placeholder: "Dimension in mm", pattern: /^(?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 7 },
        { name: 'y_axis', label: 'Y-Axis', type: 'text', placeholder: "Dimension in mm", pattern: /^(?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 7 },
        { name: 'z_axis', label: 'Z-Axis', type: 'text', placeholder: "Dimension in mm", pattern: /^(?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 7 },
        { name: 'distance_between_spindles', label: 'Distance Between Spindles', type: 'text', placeholder: "Dimension in mm", pattern: /^(?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 7 },
        { name: 'tool_change_system', label: 'Tool Change System', type: 'select', placeholder: "Please choose type", options: [{ value: 'Twin Taper', label: 'Twin Taper' }, { value: 'Direct Pickup', label: 'Direct Pickup' }] },
        { name: 'tool_shank_type', label: 'Tool Shank Type', type: 'text', placeholder: "Enter in BT40", pattern: /^(?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 7 },
        { name: 'cnc_control', label: 'CNC Control', type: 'select', placeholder: "Please choose type", options: [{ value: 'Fanuc', label: 'Fanuc' }, { value: 'Siemens', label: 'Siemens' }] },
        { name: 'automatic_pallet_changer', label: 'Automatic Pallet Changer', type: 'select', placeholder: "Please choose type", options: [{ value: 'Linear', label: 'Linear' }, { value: 'Rotary', label: 'Rotary' }, { value: 'Disc Miles', label: 'Disc Miles' }, { value: 'Others', label: 'Others' }] },
        { name: 'ppk', label: 'PPK', type: 'text', placeholder: "Enter in number", pattern: /^(?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 7 },

        { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate in Rupees", pattern: /^(?:\d{1,5}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 8 },
        { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine", pattern: /^\d{1,3}$/ },
    ],
    HorizontalMachiningCenters: [
        { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand', pattern: /^[a-zA-Z0-9\s]+$/, maxLength: 50 },
        { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model', pattern: /^[a-zA-Z0-9\s]+$/, maxLength: 50 },
        { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase', pattern: /^[0-9]{4}$/, maxLength: 4 },
        { name: 'duty', label: 'Duty', type: 'select', placeholder: "Please choose type", options: [{ value: 'Manual', label: 'Manual' }, { value: 'Light', label: 'Light' }, { value: 'Medium', label: 'Medium' }, { value: 'Heavy', label: 'Heavy' }] },
        { name: 'no_of_axis', label: 'No. Of Axis', type: 'text', placeholder: "Enter in number", pattern: /^[0-9]{0,4}$/, maxLength: 4 },
        { name: 'table_size', label: 'Table Size', type: 'text', placeholder: "Dimension in mm", pattern: /^(?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 7 },
        { name: 'max_load_on_the_table', label: 'Max Load_on The Table', type: 'text', placeholder: "Enter in kgs", pattern: /^(?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 7 },
        { name: 'x_axis', label: 'X-Axis', type: 'text', placeholder: "Dimension in mm", pattern: /^(?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 7 },
        { name: 'y_axis', label: 'Y-Axis', type: 'text', placeholder: "Dimension in mm", pattern: /^(?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 7 },
        { name: 'z_axis', label: 'Z-Axis', type: 'text', placeholder: "Dimension in mm", pattern: /^(?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 7 },
        { name: 'distance_between_spindles', label: 'Distance Between Spindles', type: 'text', placeholder: "Dimension in mm", pattern: /^(?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 7 },
        { name: 'tool_change_system', label: 'Tool Change System', type: 'select', placeholder: "Please choose type", options: [{ value: 'Twin Taper', label: 'Twin Taper' }, { value: 'Direct Pickup', label: 'Direct Pickup' }] },
        { name: 'tool_shank_type', label: 'Tool Shank Type', type: 'text', placeholder: "Enter in BT40", pattern: /^(?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 7 },
        { name: 'cnc_control', label: 'CNC Control', type: 'select', placeholder: "Please choose type", options: [{ value: 'Fanuc', label: 'Fanuc' }, { value: 'Siemens', label: 'Siemens' }] },
        { name: 'automatic_pallet_changer', label: 'Automatic Pallet Changer', type: 'select', placeholder: "Please choose type", options: [{ value: 'Linear', label: 'Linear' }, { value: 'Rotary', label: 'Rotary' }, { value: 'Disc Miles', label: 'Disc Miles' }, { value: 'Others', label: 'Others' }] },
        { name: 'ppk', label: 'PPK', type: 'text', placeholder: "Enter in number", pattern: /^(?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 7 },

        { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate in Rupees", pattern: /^(?:\d{1,5}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 8 },
        { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine", pattern: /^\d{1,3}$/ },
    ],
    DrillTapMachiningCenters: [
        { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand', pattern: /^[a-zA-Z0-9\s]+$/, maxLength: 50 },
        { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model', pattern: /^[a-zA-Z0-9\s]+$/, maxLength: 50 },
        { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase', pattern: /^[0-9]{4}$/, maxLength: 4 },
        { name: 'duty', label: 'Duty', type: 'select', placeholder: "Please choose type", options: [{ value: 'Manual', label: 'Manual' }, { value: 'Light', label: 'Light' }, { value: 'Medium', label: 'Medium' }, { value: 'Heavy', label: 'Heavy' }] },
        { name: 'no_of_axis', label: 'No. Of Axis', type: 'text', placeholder: "Enter in number", pattern: /^[0-9]{0,4}$/, maxLength: 4 },
        { name: 'table_size', label: 'Table Size', type: 'text', placeholder: "Dimension in mm", pattern: /^(?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 7 },
        { name: 'max_load_on_the_table', label: 'Max Load_on The Table', type: 'text', placeholder: "Enter in kgs", pattern: /^(?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 7 },
        { name: 'x_axis', label: 'X-Axis', type: 'text', placeholder: "Dimension in mm", pattern: /^(?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 7 },
        { name: 'y_axis', label: 'Y-Axis', type: 'text', placeholder: "Dimension in mm", pattern: /^(?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 7 },
        { name: 'z_axis', label: 'Z-Axis', type: 'text', placeholder: "Dimension in mm", pattern: /^(?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 7 },
        { name: 'distance_between_spindles', label: 'Distance Between Spindles', type: 'text', placeholder: "Dimension in mm", pattern: /^(?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 7 },
        { name: 'tool_change_system', label: 'Tool Change System', type: 'select', placeholder: "Please choose type", options: [{ value: 'Twin Taper', label: 'Twin Taper' }, { value: 'Direct Pickup', label: 'Direct Pickup' }] },
        { name: 'tool_shank_type', label: 'Tool Shank Type', type: 'text', placeholder: "Enter in BT40", pattern: /^(?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 7 },
        { name: 'cnc_control', label: 'CNC Control', type: 'select', placeholder: "Please choose type", options: [{ value: 'Fanuc', label: 'Fanuc' }, { value: 'Siemens', label: 'Siemens' }] },
        { name: 'automatic_pallet_changer', label: 'Automatic Pallet Changer', type: 'select', placeholder: "Please choose type", options: [{ value: 'Linear', label: 'Linear' }, { value: 'Rotary', label: 'Rotary' }, { value: 'Disc Miles', label: 'Disc Miles' }, { value: 'Others', label: 'Others' }] },
        { name: 'ppk', label: 'PPK', type: 'text', placeholder: "Enter in number", pattern: /^(?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 7 },

        { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate in Rupees", pattern: /^(?:\d{1,5}(?:\.\d{1,2})?|\.\d{1,2})$/, maxLength: 8 },
        { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine", pattern: /^\d{1,3}$/ },
    ],
}