export const machineFields = {
    Cutting: {
        BandSaw: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'type', label: 'Type', type: 'select', placeholder: "Please choose type", options: ['Manual', 'Automatic'] },
            { name: 'max_diameter_round_in_mm', label: 'Max Diameter Round', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_square_in_mm', label: 'Max Square', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_cut_feed_length_in_mm', label: 'Max Cut Feed Length', type: 'text', placeholder: "Dimension in mm" },
            { name: 'cutter_motor_power_in_kw', label: 'Cutter Motor Power', type: 'text', placeholder: "Enter in Kw" },
            { name: 'cutting_speed_in_mmin', label: 'Cutting Speed', type: 'text', placeholder: "Enter in m/min" },
            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ],
        PowerHackSaw: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'type', label: 'Type', type: 'select', placeholder: "Please choose type", options: ['Manual', 'Automatic'] },
            { name: 'max_diameter_in_mm', label: 'Max Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_square_in_mm', label: 'Max Square', type: 'text', placeholder: "Dimension in mm" },
            { name: 'stroke_length_in_mm', label: 'Stroke Length', type: 'text', placeholder: "Dimension in mm" },
            { name: 'no_of_speed_strokes', label: 'No. Of Speed Strokes', type: 'text', placeholder: "Enter in number" },
            { name: 'blade_thickness_in_mm', label: 'Blade Thickness', type: 'text', placeholder: "Dimension in mm" },
            { name: 'bundling_possible', label: 'Bundling Possible', type: 'select', placeholder: "Please choose type", options: ['Yes', 'No'] },
            { name: 'cutter_motor_power_in_kw', label: 'Cutter Motor Power', type: 'text', placeholder: "Enter in Kw" },
            { name: 'cutting_speed', label: 'Cutting Speed', type: 'text', placeholder: "Enter in Strokes/min" },
            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ],
        CircularSaw: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'type', label: 'Type', type: 'select', placeholder: "Please choose type", options: ['Manual', 'Automatic'] },
            { name: 'min_diameter_round_in_mm', label: 'Min Diameter Round', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_diameter_round_in_mm', label: 'Max Diameter Round', type: 'text', placeholder: "Dimension in mm" },
            { name: 'min_square_in_mm', label: 'Min Square', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_square_in_mm', label: 'Max Square', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_cut_feed_length_in_mm', label: 'Max Cut Feed Length', type: 'text', placeholder: "Dimension in mm" },
            { name: 'cutter_motor_power_in_kw', label: 'Cutter Motor Power', type: 'text', placeholder: "Enter in Kw" },
            { name: 'cutting_speed_in_mmin', label: 'Cutting Speed', type: 'text', placeholder: "Enter in m/min" },
            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ],
    },
    Drilling: {
        ConventionalDrillingMachine: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'type', label: 'Type', type: 'select', placeholder: "Please choose type", options: ['Bench', 'Pillar', 'Column Type', 'Deep Hole'] },
            { name: 'max_diameter_drill_in_mm', label: 'Max Diameter of the Drill', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_length_in_mm', label: 'Max Length', type: 'text', placeholder: "Dimension in mm" },
            { name: 'spindle_tape', label: 'Spindle Tape', type: 'text', placeholder: "Dimension in MT3" },
            { name: 'no_of_spindle_speeds', label: 'No Of Spindle Speeds', type: 'text', placeholder: "Enter in number" },
            { name: 'spindle_travel', label: 'Spindle Travel', type: 'text', placeholder: "Dimension in mm" },
            { name: 'type_of_feed', label: 'Type Of Feed', type: 'select', placeholder: "Please choose type", options: ['Manual', 'CNC'] },
            { name: 'taping_possible', label: 'Taping Possible', type: 'select', placeholder: "Please choose type", options: ['Yes', 'No'] },
            { name: 'ppk', label: 'PPK', type: 'text', placeholder: "Enter in number" },

            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ]
    },
    Machining: {
        VerticalMachiningCenters: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'duty', label: 'Duty', type: 'select', placeholder: "Please choose type", options: ['Light', 'Medium', 'Heavy'] },
            { name: 'no_of_axis', label: 'No. Of Axis', type: 'text', placeholder: "Enter in number" },
            { name: 'table_size', label: 'Table Size', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_load_on_the_table', label: 'Max Load_on The Table', type: 'text', placeholder: "Enter in kgs" },
            { name: 'x_axis', label: 'X-Axis', type: 'text', placeholder: "Dimension in mm" },
            { name: 'y_axis', label: 'Y-Axis', type: 'text', placeholder: "Dimension in mm" },
            { name: 'z_axis', label: 'Z-Axis', type: 'text', placeholder: "Dimension in mm" },
            { name: 'distance_between_spindles', label: 'Distance Between Spindles', type: 'text', placeholder: "Dimension in mm" },
            { name: 'tool_change_system', label: 'Tool Change System', type: 'select', placeholder: "Please choose type", options: ['Twin Taper', 'Direct Pickup'] },
            { name: 'tool_shank_type', label: 'Tool Shank Type', type: 'text', placeholder: "Enter in BT40" },
            { name: 'cnc_control', label: 'CNC Control', type: 'select', placeholder: "Please choose type", options: ['Fanuc', 'Siemens'] },
            { name: 'automatic_pallet_changer', label: 'Automatic Pallet Changer', type: 'select', placeholder: "Please choose type", options: ['Linear', 'Rotary', 'Disc Miles', 'Others'] },
            { name: 'ppk', label: 'PPK', type: 'text', placeholder: "Enter in number" },

            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ],
        HorizontalMachiningCenters: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'duty', label: 'Duty', type: 'select', placeholder: "Please choose type", options: ['Light', 'Medium', 'Heavy'] },
            { name: 'no_of_axis', label: 'No. Of Axis', type: 'text', placeholder: "Enter in number" },
            { name: 'table_size', label: 'Table Size', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_load_on_the_table', label: 'Max Load_on The Table', type: 'text', placeholder: "Enter in kgs" },
            { name: 'x_axis', label: 'X-Axis', type: 'text', placeholder: "Dimension in mm" },
            { name: 'y_axis', label: 'Y-Axis', type: 'text', placeholder: "Dimension in mm" },
            { name: 'z_axis', label: 'Z-Axis', type: 'text', placeholder: "Dimension in mm" },
            { name: 'distance_between_spindles', label: 'Distance Between Spindles', type: 'text', placeholder: "Dimension in mm" },
            { name: 'tool_change_system', label: 'Tool Change System', type: 'select', placeholder: "Please choose type", options: ['Twin Taper', 'Direct Pickup'] },
            { name: 'tool_shank_type', label: 'Tool Shank Type', type: 'text', placeholder: "Enter in BT40" },
            { name: 'cnc_control', label: 'CNC Control', type: 'select', placeholder: "Please choose type", options: ['Fanuc', 'Siemens'] },
            { name: 'automatic_pallet_changer', label: 'Automatic Pallet Changer', type: 'select', placeholder: "Please choose type", options: ['Linear', 'Rotary', 'Disc Miles', 'Others'] },
            { name: 'ppk', label: 'PPK', type: 'text', placeholder: "Enter in number" },

            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ],
        DrillTapMachiningCenters: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'duty', label: 'Duty', type: 'select', placeholder: "Please choose type", options: ['Light', 'Medium', 'Heavy'] },
            { name: 'no_of_axis', label: 'No. Of Axis', type: 'text', placeholder: "Enter in number" },
            { name: 'table_size', label: 'Table Size', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_load_on_the_table', label: 'Max Load_on The Table', type: 'text', placeholder: "Enter in kgs" },
            { name: 'x_axis', label: 'X-Axis', type: 'text', placeholder: "Dimension in mm" },
            { name: 'y_axis', label: 'Y-Axis', type: 'text', placeholder: "Dimension in mm" },
            { name: 'z_axis', label: 'Z-Axis', type: 'text', placeholder: "Dimension in mm" },
            { name: 'distance_between_spindles', label: 'Distance Between Spindles', type: 'text', placeholder: "Dimension in mm" },
            { name: 'tool_change_system', label: 'Tool Change System', type: 'select', placeholder: "Please choose type", options: ['Twin Taper', 'Direct Pickup'] },
            { name: 'tool_shank_type', label: 'Tool Shank Type', type: 'text', placeholder: "Enter in BT40" },
            { name: 'cnc_control', label: 'CNC Control', type: 'select', placeholder: "Please choose type", options: ['Fanuc', 'Siemens'] },
            { name: 'automatic_pallet_changer', label: 'Automatic Pallet Changer', type: 'select', placeholder: "Please choose type", options: ['Linear', 'Rotary', 'Disc Miles', 'Others'] },
            { name: 'ppk', label: 'PPK', type: 'text', placeholder: "Enter in number" },

            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ],
    },
    Turning: {
        ConventionalLathe: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'duty', label: 'Duty', type: 'select', placeholder: "Please choose type", options: ['Light', 'Medium', 'Heavy'] },
            { name: 'max_diameter_in_mm', label: 'Max Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_length_in_mm', label: 'Max Length', type: 'text', placeholder: "Dimension in mm" },
            { name: 'no_of_speeds', label: 'No Of Speeds', type: 'text', placeholder: "Enter in number" },
            { name: 'cutter_motor_power_in_kw', label: 'Cutter Motor Power', type: 'text', placeholder: "Enter in Kw" },
            { name: 'cutting_speed_in_mmin', label: 'Cutting Speed', type: 'text', placeholder: "Enter in m/min" },

            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ],
        CncLathe: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'cncControl', label: 'CNC Control', type: 'select', placeholder: "Please choose type", options: ['Fanuc', 'Siemens', 'Others'] },
            { name: 'max_turning_diameter_in_mm', label: 'Max Turning Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_turning_length_in_mm', label: 'Max Turning Length', type: 'text', placeholder: "Dimension in mm" },
            { name: 'standard_chuck_size', label: 'Standard Chuck Size', type: 'text', placeholder: "Dimension in mm" },
            { name: 'no_of_tool_station', label: 'No Of Tool Stations', type: 'text', placeholder: "Enter in number" },
            { name: 'max_boring_dia_in_mm', label: 'Max Boring Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'od_turning_tool_size', label: 'OD Turning Tool Size', type: 'text', placeholder: "Dimension in mm" },
            { name: 'positioning_accuracy', label: 'Positioning Accuracy', type: 'text', placeholder: "+/- in mm" },
            { name: 'repeatability', label: 'Repeatability', type: 'text', placeholder: "Dimension in mm" },
            { name: 'resolution', label: 'Resolution', type: 'text', placeholder: "Dimension in mm" },
            { name: 'ppk', label: 'PPK', type: 'text', placeholder: "Enter in value" },

            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ],
        TurretLathe: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'cncControl', label: 'CNC Control', type: 'select', placeholder: "Please choose type", options: ['Fanuc', 'Siemens', 'Others'] },
            { name: 'max_turning_diameter_in_mm', label: 'Max Turning Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_turning_length_in_mm', label: 'Max Turning Length', type: 'text', placeholder: "Dimension in mm" },
            { name: 'collet_bar_capacity', label: 'Collet Bar Capacity', type: 'text', placeholder: "Dimension in mm" },
            { name: 'no_of_tool_station', label: 'No Of Tool Stations', type: 'text', placeholder: "Enter in number" },
            { name: 'quill_dia_in_mm', label: 'Quill Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'quill_stroke_dia_in_mm', label: 'Quill Stroke Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'positioning_accuracy', label: 'Positioning Accuracy', type: 'text', placeholder: "+/- in mm" },
            { name: 'repeatability', label: 'Repeatability', type: 'text', placeholder: "Dimension in mm" },
            { name: 'resolution', label: 'Resolution', type: 'text', placeholder: "Dimension in mm" },
            { name: 'ppk', label: 'PPK', type: 'text', placeholder: "Enter in value" },

            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ],
        CapstanLathe: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'cncControl', label: 'CNC Control', type: 'select', placeholder: "Please choose type", options: ['Fanuc', 'Siemens', 'Others'] },
            { name: 'max_turning_diameter_in_mm', label: 'Max Turning Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_turning_length_in_mm', label: 'Max Turning Length', type: 'text', placeholder: "Dimension in mm" },
            { name: 'collet_bar_capacity', label: 'Collet Bar Capacity', type: 'text', placeholder: "Dimension in mm" },
            { name: 'no_of_tool_station', label: 'No Of Tool Stations', type: 'text', placeholder: "Enter in number" },
            { name: 'effective_stroke_dia_in_mm', label: 'Effective Stroke Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'positioning_accuracy', label: 'Positioning Accuracy', type: 'text', placeholder: "+/- in mm" },
            { name: 'repeatability', label: 'Repeatability', type: 'text', placeholder: "Dimension in mm" },
            { name: 'resolution', label: 'Resolution', type: 'text', placeholder: "Dimension in mm" },
            { name: 'ppk', label: 'PPK', type: 'text', placeholder: "Enter in value" },

            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ],
        Automat: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'max_turning_diameter_in_mm', label: 'Max Turning Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_turning_length_in_mm', label: 'Max Turning Length', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_thread_dia_in_mm', label: 'Max Thread Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'no_of_spindle_speeds', label: 'No Of Spindle Speeds', type: 'text', placeholder: "Enter in number" },
            { name: 'no_of_bars', label: 'Bar Loader(No Of Bars)', type: 'text', placeholder: "Enter in number" },
            { name: 'length_bar_in_mm', label: 'Length of the Bar(Max)', type: 'text', placeholder: "Dimension in mm" },

            { name: 'repeatability', label: 'Repeatability', type: 'text', placeholder: "Dimension in mm" },
            { name: 'ppk', label: 'PPK', type: 'text', placeholder: "Enter in value" },

            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ],
        SlidingHeadAutomat: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'max_turning_diameter_in_mm', label: 'Max Turning Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_turning_length_in_mm', label: 'Max Turning Length', type: 'text', placeholder: "Dimension in mm" },
            { name: 'spindle_through_hole_dia_in_mm', label: 'Spindle Through Hole Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'no_of_tools', label: 'No Of Tools(Max)', type: 'text', placeholder: "Enter in number" },
            { name: 'no_of_bars', label: 'Bar Loader(No Of Bars)', type: 'text', placeholder: "Enter in number" },
            { name: 'length_bar_in_mm', label: 'Length of the Bar(Max)', type: 'text', placeholder: "Dimension in mm" },

            { name: 'repeatability', label: 'Repeatability', type: 'text', placeholder: "Dimension in mm" },
            { name: 'ppk', label: 'PPK', type: 'text', placeholder: "Enter in value" },

            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ],
        MultispindleAutomat: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'max_turning_diameter_in_mm', label: 'Max Turning Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_turning_length_in_mm', label: 'Max Turning Length', type: 'text', placeholder: "Dimension in mm" },
            { name: 'no_of_spindle', label: 'No of Spindle', type: 'text', placeholder: "Enter in number" },
            { name: 'no_of_bars', label: 'Bar Loader(No Of Bars)', type: 'text', placeholder: "Enter in number" },
            { name: 'length_bar_in_mm', label: 'Length of the Bar(Max)', type: 'text', placeholder: "Dimension in mm" },

            { name: 'ppk', label: 'PPK', type: 'text', placeholder: "Enter in value" },
            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ],
        VerticalTurningLathe: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'type', label: 'Type', type: 'select', placeholder: "Please choose type", options: ['Ram Type', 'Turret type'] },
            { name: 'max_turning_diameter_in_mm', label: 'Max Turning Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_height_workplace_in_mm', label: 'Max Height of Workplace', type: 'text', placeholder: "Dimension in mm" },
            { name: 'table_dia_in_mm', label: 'Table Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_weight_workplace_in_mm', label: 'Max Weight of Workplace', type: 'text', placeholder: "Dimension in mm" },
            { name: 'no_of_tool_station', label: 'No Of Tool Stations', type: 'text', placeholder: "Enter in number" },
            { name: 'max_tool_size_dia_in_mm', label: 'Max Tool Size', type: 'text', placeholder: "Dimension in mm" },
            { name: 'cncControl', label: 'CNC Control', type: 'select', placeholder: "Please choose type", options: ['Fanuc', 'Siemens', 'Others'] },
            { name: 'positioning_accuracy', label: 'Positioning Accuracy', type: 'text', placeholder: "+/- in mm" },
            { name: 'repeatability', label: 'Repeatability', type: 'text', placeholder: "Dimension in mm" },
            { name: 'resolution', label: 'Resolution', type: 'text', placeholder: "Dimension in mm" },
            { name: 'ppk', label: 'PPK', type: 'text', placeholder: "Enter in value" },

            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ]
    },
    Grinding: {
        CylindricalGrindingMachine: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'type', label: 'Type', type: 'select', placeholder: "Please choose type", options: ['Manual', 'CNC'] },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'swing_diameter_in_mm', label: 'Swing Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'distance_between_centers_in_mm', label: 'Distance Between Centers', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_weight_workplace_in_kg', label: 'Max Weight of Workplace (in Kg/s)', type: 'text', placeholder: "Dimension in kg" },
            { name: 'max_grinding_dia_in_mm', label: 'Max Grinding Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_grinding_length_in_mm', label: 'Max Grinding Length', type: 'text', placeholder: "Dimension in mm" },
            { name: 'angular_grinding_facility', label: 'Angular Grinding Facility', type: 'select', placeholder: "Please choose type", options: ['Yes', 'No'] },
            { name: 'cncControl', label: 'CNC Control', type: 'select', placeholder: "Please choose type", options: ['Fanuc', 'Siemens'] },
            { name: 'ppk', label: 'PPK', type: 'text', placeholder: "Enter in number" },

            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ],
        InternalGrindingMachine: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'type', label: 'Type', type: 'select', placeholder: "Please choose type", options: ['Manual', 'CNC'] },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'swing_diameter_in_mm', label: 'Swing Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'distance_between_centers_in_mm', label: 'Distance Between Centers', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_weight_workplace_in_kg', label: 'Max Weight of Workplace (in Kg/s)', type: 'text', placeholder: "Dimension in kg" },
            { name: 'max_grinding_dia_in_mm', label: 'Max Grinding Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_grinding_length_in_mm', label: 'Max Grinding Length', type: 'text', placeholder: "Dimension in mm" },
            { name: 'cncControl', label: 'CNC Control', type: 'select', placeholder: "Please choose type", options: ['Fanuc', 'Siemens'] },
            { name: 'ppk', label: 'PPK', type: 'text', placeholder: "Enter in number" },

            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ],
        CenterlessGrindingMachine: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'type', label: 'Type', type: 'select', placeholder: "Please choose type", options: ['Manual', 'CNC'] },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'max_grinding_dia_in_mm', label: 'Max Grinding Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'min_grinding_dia_in_mm', label: 'Min Grinding Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'grinding_wheel_width_in_mm', label: 'Grinding Wheel Width', type: 'text', placeholder: "Dimension in mm" },
            { name: 'grinding_wheel_dia_in_mm', label: 'Grinding Wheel Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'cncControl', label: 'CNC Control', type: 'select', placeholder: "Please choose type", options: ['Fanuc', 'Siemens'] },
            { name: 'ppk', label: 'PPK', type: 'text', placeholder: "Enter in number" },

            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ]
    },
    Milling: {
        ConventionalMillingMachine: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'type', label: 'Type', type: 'select', placeholder: "Please choose type", options: ['Horizontal', 'Vertical'] },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'table_size_in_mm', label: 'Table Size', type: 'text', placeholder: "Dimension in mm" },
            { name: 'no_of_t_slots', label: 'No of T slots', type: 'text', placeholder: "Enter in number" },
            { name: 'swivel_of_table', label: 'Swivel of Table', type: 'text', placeholder: "Enter in degrees" },
            { name: 'standard_arbor_size', label: 'Standard Arbor Size', type: 'text', placeholder: "Enter in inches" },
            { name: 'longitudinal_travel', label: 'Longitudinal Travel', type: 'text', placeholder: "Dimension in mm" },
            { name: 'vertical_travel', label: 'Vertical Travel', type: 'text', placeholder: "Dimension in mm" },
            { name: 'cross_travel', label: 'Cross Travel', type: 'text', placeholder: "Dimension in mm" },
            { name: 'quill_spindle_dia_in_mm', label: 'Quill Spindle Dia', type: 'text', placeholder: "Dimension in mm" },
            { name: 'type_of_feed', label: 'Type Of Feed', type: 'select', placeholder: "Please choose type", options: ['Manual', 'Automated'] },
            { name: 'ppk', label: 'PPK', type: 'text', placeholder: "Enter in number" },

            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ]
    },
    Plastics: {
        InjectionMouldingMachine: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'type', label: 'Type', type: 'select', placeholder: "Please choose type", options: ['Horizontal', 'Vertical', 'Two Shot', 'Multi Shot', 'Micro'] },
            { name: 'clamping_unit', label: 'Clamping Unit', type: 'select', placeholder: "Please choose type", options: ['Hydraulic', 'Electric', 'Hybrid'] },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'shot_weight_in_gms', label: 'Shot Weight (in gms)', type: 'text', placeholder: "Enter in gms" },
            { name: 'screw_dia_in_mm', label: 'Screw Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'injection_rate_in_cc/s', label: 'Injection Rate', type: 'text', placeholder: "Enter in cc/s" },
            { name: 'hopper_capacity_in_litres', label: 'Hopper Capacity', type: 'text', placeholder: "Enter in litres" },
            { name: 'clamping_force_in_tons', label: 'Clamping Force', type: 'text', placeholder: "Enter in tons" },
            { name: 'mold_thickness_in_mm', label: 'Mold Thickness (min-max)', type: 'text', placeholder: "Dimension in mm" },
            { name: 'daylight_opening_in_mm', label: 'Daylight Opening', type: 'text', placeholder: "Dimension in mm" },
            { name: 'space_between_tie_bars_in_mm', label: 'Space Between Tie Bars (HxIV)', type: 'text', placeholder: "Dimension in mm" },
            { name: 'ppk', label: 'PPK', type: 'text', placeholder: "Enter in number" },

            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ],
        BlowMouldingMachine: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'type', label: 'Type', type: 'select', placeholder: "Please choose type", options: ['Accumulator Type', 'Ring Drum'] },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'no_layers_possible', label: 'No of Layers Possible', type: 'text', placeholder: "Enter in number" },
            { name: 'cosextrusion_possible', label: 'Coextrusion Possible', type: 'select', placeholder: "Please choose type", options: ['Yes', 'No'] },
            { name: 'arctic_max_size_in_litres', label: 'Arctic Max Size', type: 'text', placeholder: "Enter in litres" },
            { name: 'production_range_in_litres', label: 'Production Range', type: 'text', placeholder: "Enter in litres" },
            { name: 'max_weight_in_kg', label: 'Maximum Weight', type: 'text', placeholder: "Enter in kg" },
            { name: 'clamping_force_in_kn', label: 'Clamping Force (in KN)', type: 'text', placeholder: "Enter in KN" },
            { name: 'mold_envelope_height_in_mm', label: 'Mold Envelope Height', type: 'text', placeholder: "Dimension in mm" },
            { name: 'width_in_mm', label: 'Width', type: 'text', placeholder: "Dimension in mm" },
            { name: 'thickness_in_mm', label: 'Thickness', type: 'text', placeholder: "Dimension in mm" },
            { name: 'ppk', label: 'PPK', type: 'text', placeholder: "Enter in number" },

            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ]
    }
}

// MachiningCenters PlasticsMouldingMachines