export const machineFields = {
    Cutting: {
        BandSaw: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'type', label: 'Type', type: 'select', placeholder: "Please choose type", options: ['Manual', 'Automatic'] },
            { name: 'max_diameter_round_in_mm', label: 'Max Diameter Round', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_square_in_mm', label: 'Max Square', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_cut_feed_length_in_mm', label: 'Max Cut Feed Length', type: 'text', placeholder: "Dimension in mm" },
            { name: 'cutter_motor_power_in_kw', label: 'Cutter Motor Power', type: 'text', placeholder: "Enter in Kw" },
            { name: 'cutting_speed_in_mmin', label: 'Cutting Speed', type: 'text', placeholder: "Enter in m/min" },
            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ],
        PowerHackSaw: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'type', label: 'Type', type: 'select', placeholder: "Please choose type", options: ['Manual', 'Automatic'] },
            { name: 'max_diameter_in_mm', label: 'Max Diameter', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_square_in_mm', label: 'Max Square', type: 'text', placeholder: "Dimension in mm" },
            { name: 'stroke_length_in_mm', label: 'Stroke Length', type: 'text', placeholder: "Dimension in mm" },
            { name: 'no_of_speed_strokes', label: 'No. Of Speed Strokes', type: 'text', placeholder: "Enter in number" },
            { name: 'blade_thickness_in_mm', label: 'Blade Thickness', type: 'text', placeholder: "Dimension in mm" },
            { name: 'bundling_possible', label: 'Bundling Possible', type: 'select', placeholder: "Please choose type", options: ['Yes', 'No'] },
            { name: 'cutter_motor_power_in_kw', label: 'Cutter Motor Power', type: 'text', placeholder: "Enter in Kw" },
            { name: 'cutting_speed', label: 'Cutting Speed', type: 'text', placeholder: "Enter in Strokes/min" },
            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ],
        CircularSaw: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'type', label: 'Type', type: 'select', placeholder: "Please choose type", options: ['Manual', 'Automatic'] },
            { name: 'min_diameter_round_in_mm', label: 'Min Diameter Round', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_diameter_round_in_mm', label: 'Max Diameter Round', type: 'text', placeholder: "Dimension in mm" },
            { name: 'min_square_in_mm', label: 'Min Square', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_square_in_mm', label: 'Max Square', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_cut_feed_length_in_mm', label: 'Max Cut Feed Length', type: 'text', placeholder: "Dimension in mm" },
            { name: 'cutter_motor_power_in_kw', label: 'Cutter Motor Power', type: 'text', placeholder: "Enter in Kw" },
            { name: 'cutting_speed_in_mmin', label: 'Cutting Speed', type: 'text', placeholder: "Enter in m/min" },
            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ],
    },
    Drilling: {
        ConventionalDrillingMachine: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'type', label: 'Type', type: 'select', placeholder: "Please choose type", options: ['Bench', 'Pillar', 'Column Type', 'Deep Hole'] },
            { name: 'max_diameter_drill_in_mm', label: 'Max Diameter of the Drill', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_length_in_mm', label: 'Max Length', type: 'text', placeholder: "Dimension in mm" },
            { name: 'spindle_tape', label: 'Spindle Tape', type: 'text', placeholder: "Dimension in MT3" },
            { name: 'no_of_spindle_speeds', label: 'No Of Spindle Speeds', type: 'text', placeholder: "Enter in number" },
            { name: 'spindle_travel', label: 'Spindle Travel', type: 'text', placeholder: "Dimension in mm" },
            { name: 'type_of_feed', label: 'Type Of Feed', type: 'select', placeholder: "Please choose type", options: ['Manual', 'CNC'] },
            { name: 'taping_possible', label: 'Taping Possible', type: 'select', placeholder: "Please choose type", options: ['Yes', 'No'] },
            { name: 'ppk', label: 'PPK', type: 'text', placeholder: "Enter in number" },

            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ]
    },
    MachiningCenters: {
        VerticalMachiningCenters: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'duty', label: 'Duty', type: 'select', placeholder: "Please choose type", options: ['Light', 'Medium', 'Heavy'] },
            { name: 'no_of_axis', label: 'No. Of Axis', type: 'text', placeholder: "Enter in number" },
            { name: 'table_size', label: 'Table Size', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_load_on_the_table', label: 'Max Load_on The Table', type: 'text', placeholder: "Enter in kgs" },
            { name: 'x_axis', label: 'X-Axis', type: 'text', placeholder: "Dimension in mm" },
            { name: 'y_axis', label: 'Y-Axis', type: 'text', placeholder: "Dimension in mm" },
            { name: 'z_axis', label: 'Z-Axis', type: 'text', placeholder: "Dimension in mm" },
            { name: 'distance_between_spindles', label: 'Distance Between Spindles', type: 'text', placeholder: "Dimension in mm" },
            { name: 'tool_change_system', label: 'Tool Change System', type: 'select', placeholder: "Please choose type", options: ['Twin Taper', 'Direct Pickup'] },
            { name: 'tool_shank_type', label: 'Tool Shank Type', type: 'text', placeholder: "Enter in BT40" },
            { name: 'cnc_control', label: 'CNC Control', type: 'select', placeholder: "Please choose type", options: ['Fanuc', 'Siemens'] },
            { name: 'automatic_pallet_changer', label: 'Automatic Pallet Changer', type: 'select', placeholder: "Please choose type", options: ['Linear', 'Rotary', 'Disc Miles', 'Others'] },
            { name: 'ppk', label: 'PPK', type: 'text', placeholder: "Enter in number" },

            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ],
        HorizontalMachiningCenters: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'duty', label: 'Duty', type: 'select', placeholder: "Please choose type", options: ['Light', 'Medium', 'Heavy'] },
            { name: 'no_of_axis', label: 'No. Of Axis', type: 'text', placeholder: "Enter in number" },
            { name: 'table_size', label: 'Table Size', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_load_on_the_table', label: 'Max Load_on The Table', type: 'text', placeholder: "Enter in kgs" },
            { name: 'x_axis', label: 'X-Axis', type: 'text', placeholder: "Dimension in mm" },
            { name: 'y_axis', label: 'Y-Axis', type: 'text', placeholder: "Dimension in mm" },
            { name: 'z_axis', label: 'Z-Axis', type: 'text', placeholder: "Dimension in mm" },
            { name: 'distance_between_spindles', label: 'Distance Between Spindles', type: 'text', placeholder: "Dimension in mm" },
            { name: 'tool_change_system', label: 'Tool Change System', type: 'select', placeholder: "Please choose type", options: ['Twin Taper', 'Direct Pickup'] },
            { name: 'tool_shank_type', label: 'Tool Shank Type', type: 'text', placeholder: "Enter in BT40" },
            { name: 'cnc_control', label: 'CNC Control', type: 'select', placeholder: "Please choose type", options: ['Fanuc', 'Siemens'] },
            { name: 'automatic_pallet_changer', label: 'Automatic Pallet Changer', type: 'select', placeholder: "Please choose type", options: ['Linear', 'Rotary', 'Disc Miles', 'Others'] },
            { name: 'ppk', label: 'PPK', type: 'text', placeholder: "Enter in number" },
            
            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ],
        DrillTapMachiningCenters: [
            { name: 'brand', label: 'Brand', type: 'text', placeholder: 'Enter Brand' },
            { name: 'model', label: 'Model', type: 'text', placeholder: 'Enter Model' },
            { name: 'yearOfPurchase', label: 'Year of Purchase', type: 'text', placeholder: 'Enter year of purchase' },
            { name: 'duty', label: 'Duty', type: 'select', placeholder: "Please choose type", options: ['Light', 'Medium', 'Heavy'] },
            { name: 'no_of_axis', label: 'No. Of Axis', type: 'text', placeholder: "Enter in number" },
            { name: 'table_size', label: 'Table Size', type: 'text', placeholder: "Dimension in mm" },
            { name: 'max_load_on_the_table', label: 'Max Load_on The Table', type: 'text', placeholder: "Enter in kgs" },
            { name: 'x_axis', label: 'X-Axis', type: 'text', placeholder: "Dimension in mm" },
            { name: 'y_axis', label: 'Y-Axis', type: 'text', placeholder: "Dimension in mm" },
            { name: 'z_axis', label: 'Z-Axis', type: 'text', placeholder: "Dimension in mm" },
            { name: 'distance_between_spindles', label: 'Distance Between Spindles', type: 'text', placeholder: "Dimension in mm" },
            { name: 'tool_change_system', label: 'Tool Change System', type: 'select', placeholder: "Please choose type", options: ['Twin Taper', 'Direct Pickup'] },
            { name: 'tool_shank_type', label: 'Tool Shank Type', type: 'text', placeholder: "Enter in BT40" },
            { name: 'cnc_control', label: 'CNC Control', type: 'select', placeholder: "Please choose type", options: ['Fanuc', 'Siemens'] },
            { name: 'automatic_pallet_changer', label: 'Automatic Pallet Changer', type: 'select', placeholder: "Please choose type", options: ['Linear', 'Rotary', 'Disc Miles', 'Others'] },
            { name: 'ppk', label: 'PPK', type: 'text', placeholder: "Enter in number" },
            
            { name: 'machineHourRate', label: 'Machine Hour Rate', type: 'text', placeholder: "Enter machine hour rate" },
            { name: 'noOfMachines', label: 'No. Of Machines', type: 'text', placeholder: "Enter no. of machine" },
        ],
    }
}
